apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: zdrowejedzenie-client
  name: zdrowejedzenie-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zdrowejedzenie-client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zdrowejedzenie-client
    spec:
      containers:
        - image: polsoftex.azurecr.io/zdrowejedzenie-client:latest
          name: zdrowejedzenie-client
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zdrowejedzenie-client
  name: zdrowejedzenie-client
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: zdrowejedzenie-client
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: zdrowejedzenie-client
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: zdrowejedzenie.bcb17b143e9244b5a03d.eastus.aksapp.io
      http:
        paths:
          - backend:
              serviceName: zdrowejedzenie-client
              servicePort: 8080
            path: /
          - backend:
              serviceName: zdrowejedzenie-gateway
              servicePort: 8080
            path: /gateway/(.+)
          - backend:
              serviceName: exampleproject
              servicePort: 8080
            path: /example/(.+)
#            /gateway(/|$)(.*)

